### ISSUE TITLE
Daemon wants to bind on default, privileged 53 port: conflict with version 0.9.4 of RubyDNS?

### ISSUE THREAD

**Issue by brocheafoin** [phinze/landrush#120]
Hey there,

I'd like to use landrush to handle wildcard DNS for my .dev domains, but it doesn't want to start on my machine. My interpretation of the log is that it's trying to bind the server to port 53 instead of 10053. Since this is a privileged port, the operation is refused, unless it's sudo'ed, which is not what we want.

Here is my log file:
```
=== Log Marked @ 2015-08-08 18:49:18 -0400 ===
I, [2015-08-08T18:49:18.834766 #38624]  INFO -- : Starting RubyDNS server (v0.9.4)...
I, [2015-08-08T18:49:18.835176 #38624]  INFO -- : <> Listening on udp:0.0.0.0:53
E, [2015-08-08T18:49:18.837687 #38624] ERROR -- : Actor crashed!
Errno::EACCES: Permission denied - bind(2)
	/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
E, [2015-08-08T18:49:18.838522 #38624] ERROR -- : Actor crashed!
Errno::EACCES: Permission denied - bind(2)
	/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:108:in `value'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid.rb:173:in `new'
	/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:166:in `block in run'
	/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `each'
	/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `run'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
	/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
=== Daemon Exception Backtrace @ 2015-08-08 18:49:18 -0400 ===
Errno::EACCES: Permission denied - bind(2)
/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
(celluloid):0:in `remote procedure call'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:108:in `value'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid.rb:173:in `new'
/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:166:in `block in run'
/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `each'
/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `run'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
(celluloid):0:in `remote procedure call'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:108:in `value'
/Users/qbert72/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/Users/qbert72/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns.rb:36:in `run_server'
/Users/qbert72/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/server.rb:52:in `run'
/Users/qbert72/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:92:in `block in start'
/Users/qbert72/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `fork'
/Users/qbert72/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `start'
/Users/qbert72/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:37:in `daemonize'
/Users/qbert72/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/base.rb:124:in `daemonize'
/Users/qbert72/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/command.rb:14:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
=== Daemon Crashed ===
=== Daemon Stopping @ 2015-08-08 18:49:18 -0400 ===
```

My Vagranfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant provider as Virtualbox
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

require 'yaml'

ANSIBLE_PATH = __dir__ # path targeting Ansible directory (relative to Vagrantfile)

PRIVATE_IP = '192.168.50.5'

# Set Ansible roles_path relative to Ansible directory
ENV['ANSIBLE_ROLES_PATH'] = File.join(ANSIBLE_PATH, 'vendor', 'roles')

config_file = File.join(ANSIBLE_PATH, 'group_vars/development')

if File.exists?(config_file)
  wordpress_sites = YAML.load_file(config_file)['wordpress_sites']
  raise "no sites found in #{config_file}" if wordpress_sites.to_h.empty?
else
  raise "#{config_file} file not found. Please set `ANSIBLE_PATH` in Vagrantfile"
end

Vagrant.require_version '>= 1.5.1'

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.ssh.forward_agent = true

  # Required for NFS to work, pick any local IP
  config.vm.network :private_network, ip: PRIVATE_IP

  hostname, *aliases = wordpress_sites.flat_map { |(_name, site)| site['site_hosts'] }
  config.vm.hostname = hostname
  www_aliases = ["www.#{hostname}"] + aliases.map { |host| "www.#{host}" }

  if Vagrant.has_plugin? 'landrush'
    config.landrush.enabled = true
    config.landrush.tld = config.vm.hostname

    aliases.each do |host|
      config.landrush.host host, PRIVATE_IP
    end
  else
    puts 'landrush missing, please install the plugin:'
    puts 'vagrant plugin install landrush'
  end

  if Vagrant::Util::Platform.windows?
    wordpress_sites.each do |(name, site)|
      config.vm.synced_folder local_site_path(site), remote_site_path(name), owner: 'vagrant', group: 'www-data', mount_options: ['dmode=776', 'fmode=775']
    end
  else
    if !Vagrant.has_plugin? 'vagrant-bindfs'
      raise Vagrant::Errors::VagrantError.new,
        "vagrant-bindfs missing, please install the plugin:\nvagrant plugin install vagrant-bindfs"
    else
      wordpress_sites.each do |(name, site)|
        config.vm.synced_folder local_site_path(site), nfs_path(name), type: 'nfs'
        config.bindfs.bind_folder nfs_path(name), remote_site_path(name), u: 'vagrant', g: 'www-data'
      end
    end
  end

  if Vagrant::Util::Platform.windows?
    config.vm.provision :shell do |sh|
      sh.path = File.join(ANSIBLE_PATH, 'windows.sh')
    end
  else
    config.vm.provision :ansible do |ansible|
      ansible.playbook = File.join(ANSIBLE_PATH, 'dev.yml')
      ansible.groups = {
        'web' => ['default'],
        'development' => ['default']
      }

      if vars = ENV['ANSIBLE_VARS']
        extra_vars = Hash[vars.split(',').map { |pair| pair.split('=') }]
        ansible.extra_vars = extra_vars
      end
    end
  end

  config.vm.provider 'virtualbox' do |vb|
    # Give VM access to all cpu cores on the host
    cpus = case RbConfig::CONFIG['host_os']
      when /darwin/ then `sysctl -n hw.ncpu`.to_i
      when /linux/ then `nproc`.to_i
      else 2
    end

    # Customize memory in MB
    vb.customize ['modifyvm', :id, '--memory', 1024]
    vb.customize ['modifyvm', :id, '--cpus', cpus]

    # Fix for slow external network connections
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
  end
end

def local_site_path(site)
  File.expand_path(site['local_path'], ANSIBLE_PATH)
end

def nfs_path(site_name)
  "/vagrant-nfs-#{site_name}"
end

def remote_site_path(site_name)
  File.join('/srv/www/', site_name, 'current')
end
```

Any idea what is causing this problem? Thanks in advance!

**Comment by zia-newversion** [comment]
:-1: Same issue here. For sake of diversity, log from a Linux (Ubuntu 14.04) system with Vagrant 1.7.4 is shown:

```
=== Log Marked @ 2015-08-09 04:41:38 +0500 ===
I, [2015-08-09T04:41:38.632788 #10946]  INFO -- : Starting RubyDNS server (v0.9.4)...
I, [2015-08-09T04:41:38.632993 #10946]  INFO -- : <> Listening on udp:0.0.0.0:53
E, [2015-08-09T04:41:38.634146 #10946] ERROR -- : Actor crashed!
Errno::EACCES: Permission denied - bind(2)
	/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
E, [2015-08-09T04:41:38.634615 #10946] ERROR -- : Actor crashed!
Errno::EACCES: Permission denied - bind(2)
	/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:108:in `value'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid.rb:173:in `new'
	/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:166:in `block in run'
	/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `each'
	/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `run'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
=== Daemon Exception Backtrace @ 2015-08-09 04:41:38 +0500 ===
Errno::EACCES: Permission denied - bind(2)
/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
(celluloid):0:in `remote procedure call'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:108:in `value'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid.rb:173:in `new'
/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:166:in `block in run'
/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `each'
/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `run'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
(celluloid):0:in `remote procedure call'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:108:in `value'
/home/zia/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/home/zia/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns.rb:36:in `run_server'
/home/zia/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/server.rb:52:in `run'
/home/zia/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:92:in `block in start'
/home/zia/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `fork'
/home/zia/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `start'
/home/zia/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:37:in `daemonize'
/home/zia/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/base.rb:124:in `daemonize'
/home/zia/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/command.rb:14:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
=== Daemon Crashed ===
=== Daemon Stopping @ 2015-08-09 04:41:38 +0500 ===
```

I have dnsmasq running on `:53`. On Linux machines, dnsmasq is _required_ to enable visibility on host machine. IIRC, there is no other mechanism for telling the resolver to ask `127.0.0.1:10053` for specific domains. So even if it can somehow be `sudo`ed into running on `:53` it will be essentially useless on Linux systems.

For sake of completeness, I uninstalled Vagrant 1.7.4 and installed the old 1.7.1 and then reinstalled the plugin i.e. `rm -rf ~/.vagrant.d/ && vagrant plugin install landrush` and it seems to be working fine. However there are issues with old Vagrant that have been resolved in later versions therefore _keep using the old version until it's fixed_ isn't a viable strategy either.

Please fix. :grimacing:

**Comment by brocheafoin** [comment]
Hi Zia,

Thanks for the cue about downgrading Vagrant. It helped me get my installation working. The main relevant difference I spotted is that in Vagrant 1.7.1, the Rubydns gem is version 0.7.3 whereas in Vagrant 1.7.4, the same gem is upgraded to 0.9.4. That seems like the root issue to me.

Also, don't take this the wrong way, but when I need something from an open source developer and I know I can't contribute, I try to be at my most polite. In your previous message, you are putting words in the developer's mouth ("keep using the old version until it's fixed") and you end up firing an order with a grimace. I don't think this will help our cause.

**Comment by zia-newversion** [comment]
Oh!

I am so very terribly sorry. I absolutely positively did not mean to be even slightly rude. That is unacceptable behaviour on my part. English isn't my first language so words and tones mean _slightly_ different to me. I would take the opportunity to try and explain myself.

_Keep using the old version until it's fixed_ is something that I tell myself. I didn't mean this to portray what I thought were the feelings of the developer. This is something that I tell myself on a regular basis. But that doesn't work in this case because my other self has problems with this strategy in this particular case. I guess a more accurate way to put that sentence would be:

> I usually resort to keep using the old version without complaining until the latest one is fixed, but that doesn't work for me in this case.

I absolutely had no idea :grimace: is an expression of malice. Just did a `define grimace` and found out that it was not appropriate. What I did was, I opened [this cheat sheet here](https://github.com/docker/distribution) and copied an emoji that I _thought_ meant sort of a nervous smile, as in, I am embarrassed to be asking someone else to fix something that _I_ need when at the same time I am a strong proponent of the 'no warranties expressed or implied' notion. It's hard to explain and now that I know that "grimace" doesn't really mean what I thought it meant, it's even more embarrassing.

Sincere apologies all around.

**Comment by nervo** [comment]
Being *really* rude would be to say: same issue here :)

**Comment by mheiges** [comment]
celluloid 0.16.1 released Aug 8 (a dependency of rubydns) seems to be the problem. I downgraded it to 0.16.0 and landrush is again able to start with intended non-privileged ports. I have Vagrant 1.7.4

    export GEM_HOME=~/.vagrant.d/gems
    gem uninstall celluloid -v 0.16.1
    gem install celluloid -v 0.16.0

**Comment by metcalfc** [comment]
@mheiges solution fixed this for me.

**Comment by brocheafoin** [comment]
The relevant upstream issue would be this one, then:
https://github.com/ioquatix/rubydns/issues/55

**Comment by VEnis** [comment]
@mheiges solution works for me too.

**Comment by sdellow** [comment]
@mheiges solution also works for me.

**Comment by BrianGilbert** [comment]
for those trying to figure out how to install @mheiges's update:

```
cd ~/Downloads
git clone https://github.com/metcalfc/landrush.git
cd landrush
git checkout fix_celluloid
bundle install
bundle exec rake build
cd pkg
vagrant plugin install ./landrush-0.18.0.gem

**Comment by yankcrime** [comment]
@mheiges Solution **doesn't** work for me, unfortunately.  Not really sure what's going on to be honest:

```
❯ echo $GEM_HOME
/Users/nick/.vagrant.d/gems

❯ gem list celluloid

*** LOCAL GEMS ***

celluloid (0.16.0)
celluloid-io (0.16.2)

❯ vagrant landrush status
Dumping daemon crash log:
[landrush] Daemon status: crashed
=== Daemon Exception Backtrace @ 2015-08-18 16:24:47 +0100 ===
Errno::EACCES: Permission denied - bind(2)
/Users/nick/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
/Users/nick/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
/Users/nick/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'

*snip*
```

What's odd is that backtrace is referencing a version of `celluloid` that isn't installed, e.g:

```
❯ ls -la /Users/nick/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb
ls: /Users/nick/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb: No such file or directory
```

```
❯ ruby -v ; gem -v
ruby 1.9.3p550 (2014-10-27 revision 48165) [x86_64-darwin14.0.0]
2.4.8
```

**Comment by BrianGilbert** [comment]
@yankcrime 

```
rm -rf ~/.vagrant.d/gems
 rm -r ~/.vagrant.d/plugins.json
```

Then reinstall vagrant plugins that you require..

**Comment by yankcrime** [comment]
@BrianGilbert Thanks - already tried that step and no luck, unfortunately.

**Comment by ioquatix** [comment]
My apologies, but this is an issue with RubyDNS. Please follow https://github.com/ioquatix/rubydns/issues/55 for a fix which should be coming soon.

**Comment by ioquatix** [comment]
Okay, there is a release 1.0.2 which ties RubyDNS to celluloid 0.16.0 which is an interim fix. There will be a release of RubyDNS 2.0 soon which has a better fix and also updates to celluloid 0.17.0 but that still requires a bit of work.

**Comment by metcalfc** [comment]
Updated my patch to use RubyDNS 1.0.2

**Comment by ioquatix** [comment]
Just to fill everyone in, Celluloid 0.16.1 broke semantic versioning guarantees and was not backwards compatible, hence the break. RubyDNS 1.0.2 has been locked to 0.16.0 and in addition celluloid 0.16.1 has been yanked.
