### ISSUE TITLE
"rake test" is giving error for master branch

### ISSUE THREAD

**Issue by LalatenduMohanty** [phinze/landrush#153]
Steps to reproduce

* git clone https://github.com/phinze/landrush.git
* cd landrush
* `bundle install`
* `rake test`

The test was done on Fedora 23 

```
$ rake test
/home/lmohanty/Code/landrush/test/test_helper.rb:4:in `require': cannot load such file -- minitest/spec (LoadError)
	from /home/lmohanty/Code/landrush/test/test_helper.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/lmohanty/Code/landrush/test/landrush/action/setup_test.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `each'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib" "/home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by LalatenduMohanty** [comment]
`$ bundle exec rake` is also giving following error
```
$ bundle exec rake
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.4.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
rake aborted!
LoadError: cannot load such file -- json
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/formatter/json_formatter.rb:3:in `require'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/formatter/json_formatter.rb:3:in `<top (required)>'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop.rb:334:in `require'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop.rb:334:in `<top (required)>'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:46:in `require'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:46:in `run_cli'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:38:in `run_main_task'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:30:in `block (2 levels) in initialize'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:26:in `block in initialize'
Tasks: TOP => default => rubocop
(See full trace by running task with --trace)
```

**Comment by njam** [comment]
Yes, I think minitest is missing - see https://github.com/phinze/landrush/pull/148

**Comment by LalatenduMohanty** [comment]
@njam I did add minitest to gemfile , but it lead to a new issue 

```
$ rake test
/home/lmohanty/Code/landrush-hardy/lib/landrush.rb:4:in `rescue in <top (required)>': The Vagrant landrush plugin must be run within Vagrant. (RuntimeError)
	from /home/lmohanty/Code/landrush-hardy/lib/landrush.rb:1:in `<top (required)>'
	from /home/lmohanty/Code/landrush-hardy/test/test_helper.rb:6:in `require'
	from /home/lmohanty/Code/landrush-hardy/test/test_helper.rb:6:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/lmohanty/Code/landrush-hardy/test/landrush/action/setup_test.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `each'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib" "/home/lmohanty/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]

```

**Comment by njam** [comment]
`bundle exec rake test` also?

**Comment by LalatenduMohanty** [comment]
Yes, 
```
$ bundle exec rake
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.4.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
rake aborted!
LoadError: cannot load such file -- json
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/formatter/json_formatter.rb:3:in `require'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/formatter/json_formatter.rb:3:in `<top (required)>'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop.rb:334:in `require'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop.rb:334:in `<top (required)>'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:46:in `require'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:46:in `run_cli'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:38:in `run_main_task'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:30:in `block (2 levels) in initialize'
/home/lmohanty/.gem/ruby/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:26:in `block in initialize'
Tasks: TOP => default => rubocop
(See full trace by running task with --trace)
```

**Comment by njam** [comment]
Hm, it looks like "rubocop" is requiring `json`, which fails on your system.
I thought `json` was always part of a ruby interpreter installation, but I might be wrong.
See discussion here: https://github.com/bbatsov/rubocop/pull/755

Probably you can fix it by just running `gem install json`?
I'm closing this, because it's rather a rubocop issue.
